media:
  input: assets/uploads
  output: /assets/uploads

content:
  - name: australia
    label: Australia
    type: collection
    path: _australia
    filename: "{fields.slug}.md"
    fields:
      - { name: name_fa, label: Name FA, type: string, required: true }
      - { name: slug, label: Slug, type: string, required: true }