title: مزیاب | MozYab
description: مزدوریاب در استرالیا - حامیان و مزدوران جمهوری اسلامی در استرالیا
lang: fa
markdown: kramdown

collections:
  australia:
    output: true
    permalink: /australia/:name/

defaults:
  - scope:
      path: ""
    values:
      layout: default

- scope:
      path: "MbgIoljH$gugu8BXqq"
    values:
      sitemap: false
      
plugins:
  - jekyll-sitemap
