title: Australia Directory
description: فهرست فارسی
lang: fa
markdown: kramdown

collections:
  australia:
    output: true
    permalink: /australia/:name/

defaults:
  - scope:
      path: ""
    values:
      layout: default
