backend:
  name: github
  repo: mozdooryab/mozdooryab.github.io
  branch: main

media_folder: assets/uploads
public_folder: /assets/uploads

collections:
  - name: australia
    label: Australia
    label_singular: Person
    folder: _australia
    create: true
    slug: "{{fields.slug}}"
    identifier_field: name_fa
    fields:
      - { label: Layout, name: layout, widget: hidden, default: person }
      - { label: Published (yes/no), name: published, widget: string, default: "yes", required: false }
      - { label: Name FA, name: name_fa, widget: string }
      - { label: Name EN, name: name_en, widget: string }
      - { label: Slug, name: slug, widget: string }
      - { label: City, name: city, widget: string, required: false }
      - { label: Role, name: role, widget: string, required: false }
      - { label: Email, name: email, widget: string, required: false }
      - { label: Phone, name: phone, widget: string, required: false }
      - { label: LinkedIn, name: linkedin, widget: string, required: false }
      - { label: Instagram, name: instagram, widget: string, required: false }
      - { label: Facebook, name: facebook, widget: string, required: false }
      - { label: Telegram, name: telegram, widget: string, required: false }
      - { label: Featured Image, name: featured_image, widget: image, required: false }
      - { label: Gallery Image 1, name: gallery_image_1, widget: image, required: false }
      - { label: Gallery Image 2, name: gallery_image_2, widget: image, required: false }
      - { label: Gallery Image 3, name: gallery_image_3, widget: image, required: false }
      - { label: Gallery Image 4, name: gallery_image_4, widget: image, required: false }
      - { label: Gallery Image 5, name: gallery_image_5, widget: image, required: false }
      - { label: Gallery Image 6, name: gallery_image_6, widget: image, required: false }
      - { label: Gallery Image 7, name: gallery_image_7, widget: image, required: false }
      - { label: Gallery Image 8, name: gallery_image_8, widget: image, required: false }
      - { label: Video URL 1, name: video_url_1, widget: string, required: false }
      - { label: Video URL 2, name: video_url_2, widget: string, required: false }
      - { label: Video URL 3, name: video_url_3, widget: string, required: false }
      - { label: Video URL 4, name: video_url_4, widget: string, required: false }
      - { label: Tags, name: tags_text, widget: string, required: false }
      - { label: Body, name: body, widget: markdown, required: false }
